basePath: /
definitions:
  api.APIError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  dto.CreateAccountRequest:
    properties:
      username:
        description: |-
          @Description The username of the new account.
          @Example charlie
        maxLength: 100
        minLength: 3
        type: string
    required:
    - username
    type: object
  dto.CreateCardRequest:
    properties:
      account_id:
        description: |-
          @Description Account ID to associate the new card
          @Example e252f5dd-ded2-4a30-a4a5-6e2940008d54
        type: string
    required:
    - account_id
    type: object
  models.Account:
    properties:
      created_at:
        description: |-
          @Description The creation timestamp of the account.
          @Example 2025-09-22T19:15:24.526505Z
        type: string
      id:
        description: |-
          @Description The unique identifier of the account.
          @Example 550e8400-e29b-41d4-a716-446655440000
        type: string
      updated_at:
        description: |-
          @Description The last update timestamp of the account.
          @Example 2025-09-22T19:15:24.526505Z
        type: string
      username:
        description: |-
          @Description The unique username for the account.
          @Example charlie
        type: string
    type: object
  models.Card:
    properties:
      account_id:
        description: |-
          @Description The unique identifier of the account this card belongs to.
          @Example 550e8400-e29b-41d4-a716-446655440000
        type: string
      card_token:
        description: |-
          @Description The unique, irreversible token for the card.
          @Example 5b7c16af7278094cd14bd041079111ed00fa832c8a460d8e3f40156408d99475
        type: string
      created_at:
        description: |-
          @Description The creation timestamp of the card.
          @Example 2025-09-22T19:15:24.526505Z
        type: string
      id:
        description: |-
          @Description The unique identifier of the card.
          @Example 550e8400-e29b-41d4-a716-446655440000
        type: string
      last_four_digits:
        description: |-
          @Description The last four digits of the card number for identification.
          @Example 8995
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a main payment-gateway API .
  title: Payment Gateway API
  version: "1.0"
paths:
  /accounts:
    get:
      description: Returns a list of all accounts, with pagination support.
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Account'
            type: array
      summary: Get all accounts with pagination
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Creates a new account with a username.
      parameters:
      - description: Account data for creation
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Account'
      summary: Create a new account
      tags:
      - accounts
  /cards:
    post:
      consumes:
      - application/json
      description: Creates a new, fictional card and associates it with an account.
      parameters:
      - description: Account ID to associate the new card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCardRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Card'
        "400":
          description: Invalid request body or validation failed
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Failed to create card
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Create a new card
      tags:
      - cards
schemes:
- http
swagger: "2.0"
