basePath: /
definitions:
  api.APIError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  dto.CreateAccountRequest:
    properties:
      username:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - username
    type: object
  dto.CreateCardRequest:
    properties:
      account_id:
        type: string
    required:
    - account_id
    type: object
  models.Account:
    properties:
      created_at:
        type: string
      id:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  models.Card:
    properties:
      account_id:
        type: string
      card_token:
        type: string
      created_at:
        type: string
      id:
        type: string
      last_four_digits:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a main payment-gateway API .
  title: Payment Gateway API
  version: "1.0"
paths:
  /accounts:
    get:
      description: Returns a list of all accounts, with pagination support.
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Account'
            type: array
      summary: Get all accounts with pagination
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Creates a new account with a username.
      parameters:
      - description: Account data for creation
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Account'
      summary: Create a new account
      tags:
      - accounts
  /cards:
    post:
      consumes:
      - application/json
      description: Creates a new, fictional card and associates it with an account.
      parameters:
      - description: Account ID to associate the new card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCardRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Card'
        "400":
          description: Invalid request body or validation failed
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Failed to create card
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Create a new card
      tags:
      - cards
schemes:
- http
swagger: "2.0"
