services:

  rabbitMQ:
    image: "rabbitmq:3-management"
    container_name: "rabbitMQ"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: "postgres:15"
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rust-processor:
    build:
     context: ./rust-processor
     dockerfile: Dockerfile
    container_name: "rust-processor"
    depends_on:
      - rabbitMQ
      - postgres
    env_file:
      - .env
      
volumes:
  rabbitmq_data:
  postgres_data: