services:

  go-api:
    build:
      context: ./go-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./go-api:/app
    ports:
      - "${API_PORT}:8080"
    env_file:
      - .env.development
     
  rust-processor:
    build:
      context: ./rust-processor
      dockerfile: Dockerfile.dev
    container_name: rust-processor
    volumes:
      - ./rust-processor:/app
    depends_on:
      - rabbitMQ
      - postgres
      - go-api
    env_file:
      - .env.development

  frontend:
    container_name: frontend-dev
    build:
      target: development
    ports:
      - "8082:8081"

    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - go-api
    env_file:
      - .env.development
    stdin_open: true
    tty: true
    command: ["pnpm", "dev"]