services:
  rabbitMQ:
    image: "rabbitmq:3-management"
    container_name: "rabbitMQ"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: "postgres:15"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: "user"
     POSTGRES_PASSWORD: "password"
     POSTGRES_DB: "gateway_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  rabbitmq_data:
  postgres_data: