services:

  rabbitMQ:
    image: "rabbitmq:3-management"
    container_name: "rabbitMQ"
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: "postgres:15"
    container_name: "postgres"
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rust-processor:
    build:
     context: ./rust-processor
     dockerfile: Dockerfile
    container_name: "rust-processor"
    depends_on:
      - rabbitMQ
      - postgres
      - redis
      - go-api
    env_file:
      - .env
      
  go-api:
    build:
      context: ./go-api
      dockerfile: Dockerfile
    container_name: go-api
    depends_on:
      - rabbitMQ
      - postgres
      - redis
    env_file:
      - .env
    ports:  
      - "${API_PORT}:8080"

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env

volumes:
  rabbitmq_data:
  postgres_data:
  redis_data: