CREATE TABLE accounts(
    id UUID PRIMARY KEY NOT NULL,
    username VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cards(
    id UUID PRIMARY KEY NOT NULL,
    account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
    card_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions(
    id UUID PRIMARY KEY NOT NULL,
    account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
    card_id UUID REFERENCES cards(id),
    amount_cents BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);